"""Fix missing id server_default on the AI layer's tables

0021's op.create_table calls declared `id` as primary_key=True but never
gave it server_default=gen_random_uuid() at the database level (unlike
every other table in this project, and unlike the ORM model in
app/models/ai.py, which does declare it - the model-side default only
applies when SQLAlchemy itself builds the INSERT with an autogenerated
Core Table object, not when a raw db.add(SomeModel()) goes through the ORM
unit-of-work without an explicit id, which is how app/api/routes/ai.py
creates every AITask/AIFinding/AIAgent row). Caught immediately in a smoke
test - a plain "ask a question" insert failed with a NOT NULL violation on
`id`. Not a data-loss bug (0021's own seed rows all supplied explicit ids),
just needs the same DEFAULT added a second time via ALTER.

Revision ID: 0022
Revises: 0021
Create Date: 2026-09-06

"""
from typing import Sequence, Union

from alembic import op

revision: str = "0022"
down_revision: Union[str, None] = "0021"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLES = ("ai_providers", "ai_agents", "ai_tasks", "ai_findings")


def upgrade() -> None:
    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id SET DEFAULT gen_random_uuid()")


def downgrade() -> None:
    for table in _TABLES:
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT")
